// As my plan, this file created by developers of DL Libs. Though GraphNodeId 
// of KernelMap_t can be generated by compiler, the other two's mapping cannot.

#include "../graph.h"
#include "kernel-map.h"
#include <cstdarg>
#include <cstdio>

int KF_Conv(const char *format, ...) {
  va_list args;

  va_start( args, format );
  va_end( args );

  printf("Executing KF_Conv()\n");

  return 0;
}

int KF_MaxPool(const char *format, ...) {
  printf("Executing KF_MaxPool()\n");

  return 0;
}

KernelMap_t KM[] = {
  0, "A", &KF_Conv,
  1, "B", &KF_MaxPool,
};
