# CPU and endian passed from command line, such as 
#   "make -f Makefile.slinker CPU=cpu032I endian=le"

SRCS := start.cpp debug.cpp printf-stdarg-def.c printf-stdarg.c ch_slinker.cpp \
	lib_cpu0.ll
INC_DIRS := $(SRC_DIR) ../../lbdex/input
LIBFLOAT_DIR :=
LIBS :=

include Common.mk
