# CPU and endian passed from command line, such as 
#   "make -f Makefile.sanitizer_printf CPU=cpu032II endian="

SRCS := start.cpp debug.cpp sanitizer_printf.cpp printf-stdarg-def.c ch_hello.c \
        lib_cpu0.ll
LIBBUILTINS_DIR := ../compiler-rt/
INC_DIRS := ./ ../include ../../lbdex/input $(HOME)/llvm/test/compiler-rt/lib/sanitizer_common
LIBS := $(LIBBUILTINS_DIR)/build/libbuiltins.a

include Common.mk
