# CPU and endian passed from command line, such as 
#   "make -f Makefile.printf-stdarg-2 CPU=cpu032I endian=el"
#endian :=

SRCS := start.cpp debug.cpp printf-stdarg-def.c printf-stdarg-2.cpp lib_cpu0.ll
INC_DIRS := $(SRC_DIR) ../../lbdex/input
LIBFLOAT_DIR :=
LIBS :=

include Common.mk
