# CPU and endian passed from command line, such as 
#   "make -f Makefile.ch13_1 CPU=cpu032I endian=el"
#endian :=

SRCS := start.cpp ch13_1.cpp a.cpp lib_cpu0.ll
INC_DIRS := $(SRC_DIR) ../../lbdex/input
LIB_DIR :=
LIBS :=

include Common.mk
