# CPU and endian passed from command line, such as 
#   "make -f Makefile.float CPU=cpu032II ENDIAN=el"
#   Ignore argument and set CPU to cpu032II since software float point library, 
#   libsoftfloat, only supports cpu032II at this point.

SRCS := start.cpp debug.cpp printf-stdarg-def.c printf-stdarg.c ch_float.cpp lib_cpu0.ll
INC_DIRS := ../../lbdex/input 
LIBFLOAT_DIR := ../libsoftfloat/compiler-rt
LIBS := $(LIBFLOAT_DIR)/build/libFloat.a

include Common.mk
